export const HOST_SERVER = 'http://localhost:8080' 
export const NOW_MOVIE = 'NOW' 
export const COMMING_SOON_MOVIE = 'COMMING' 
export const FETCH_DATA_SUCCESS = 'SUCCESS' 
export const FETCH_DATA_FAIL = 'FAIL' 
export const LOGIN_SUCCESS = 'Đăng nhập thành công'
export const NUMBER_MOVIE_HOME = 6
export const NUMBER_EVENT_HOME = 3
export const NUMBER_NEWS_HOME = 10
export const LITMIT_MOVIE = 8
export const TAB_USER_INFOMATION = 'INFOMATION'
export const TAB_USER_CHANGEPASSWORD = 'CHANGPASSWORD'
export const TAB_USER_GIFT = 'GIFT'
export const TAB_USER_HISTORY = 'HISTORY'
export const METHOD_PAYMENT_MOMO = 'Momo'
export const METHOD_PAYMENT_AIRPAY = 'AirPay'
export const METHOD_PAYMENT_ZALOPAY = 'ZaloPay'
export const METHOD_PAYMENT_VIETTELPAY = 'ViettelPay'
export const TAB_ADMIN_MOVIE = 'ADMIN_MOVIE'
export const TAB_ADMIN_USER = 'ADMIN_USER'
export const TAB_ADMIN_GIFT = 'ADMIN_GIFT'
export const TAB_ADMIN_MOVIETIME = 'ADMIN_MOVIETIME'
export const TAB_ADMIN_REVENUE = 'ADMIN_REVENUE'
export const TAB_ADMIN_DASHBOARD = 'ADMIN_DASHBOARD'
export const LIMIT_USER_ADMIN = 10

